GET http://localhost:5000/api/v1/movies/recommend_1?movie_id=6423942ca243ef348c1967b7
content-type:application/json

# GET http://localhost:5000/api/v1/movies/recommend_1?runtime=&_id=6423942ca243ef348c1967b6&vote_average=8.5&vote_count=50000
# content-type:application/json

# GET http://localhost:5000/api/v1/movies/?page=2&limit=10
# content-type:application/json
